version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          command: docker-compose up -d
      - run:
          command: docker exec -it -e RAILS_ENV=test project_app_1 bundle exec rake db:migrate
      - run:
          command: docker exec -it -e RAILS_ENV=test project_app_1 bundle exec rspec
